import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { randomBytes as nodeRandomBytes } from 'node:crypto';
import type { Result } from '../../shared/Result.ts';
import { err, ok } from '../../shared/Result.ts';

const DEFAULT_PORT = 8080;
const DEFAULT_DATA_DIR = './data';
const PASSWORD_BYTE_LENGTH = 24;
const ENV_FILE_MODE = 0o600;

export interface InitFlags {
  readonly domains?: string | undefined;
  readonly dataDir?: string | undefined;
  readonly port?: number | undefined;
}

export interface InitAnswers {
  readonly domains: readonly string[];
  readonly dataDir: string;
  readonly port: number;
}

function parseDomains(raw: string | undefined): readonly string[] {
  if (raw === undefined) return [];
  return raw
    .split(',')
    .map((domain) => domain.trim())
    .filter((domain) => domain.length > 0);
}

/**
 * Resolves the answers `init` needs (domains, data directory, port) either
 * from flags (used non-interactively, e.g. in a script or a test) or,
 * eventually, from interactive prompts. Kept pure so the "what do we ask,
 * what do we default to" logic never touches a real terminal.
 */
export function resolveInitAnswers(options: { readonly isInteractive: boolean; readonly flags: InitFlags }): InitAnswers {
  const { flags } = options;
  return {
    domains: parseDomains(flags.domains),
    dataDir: flags.dataDir ?? DEFAULT_DATA_DIR,
    port: flags.port ?? DEFAULT_PORT,
  };
}

/**
 * Generates a strong admin password from injected randomness. Base64url
 * encoding keeps it safe to embed in a `.env` file (and to select with a
 * double-click in a terminal) without escaping.
 */
export function generateAdminPassword(randomBytes: (size: number) => Uint8Array = nodeRandomBytes): string {
  return Buffer.from(randomBytes(PASSWORD_BYTE_LENGTH)).toString('base64url');
}

export function renderEnvFileContent(adminPassword: string): string {
  return `# Generated by \`tadoru init\`. Keep this file at mode 0600.\nTADORU_ADMIN_PASSWORD=${adminPassword}\n`;
}

export interface ConfigFileObject {
  readonly port: number;
  readonly dataDir: string;
  readonly sites: readonly string[];
  readonly trustedProxy: boolean;
  readonly retention: { readonly rawEventMonths: number };
  readonly session: { readonly inactivityMinutes: number };
}

/**
 * Builds the object written to `tadoru.config.json`. Deliberately has no
 * field for the admin password — that only ever lives in the generated
 * `.env` file — see AGENTS.md invariant on never shipping a default secret.
 */
export function buildConfigFileObject(answers: InitAnswers): ConfigFileObject {
  return {
    port: answers.port,
    dataDir: answers.dataDir,
    sites: answers.domains,
    trustedProxy: false,
    retention: { rawEventMonths: 25 },
    session: { inactivityMinutes: 30 },
  };
}

export interface PromptPort {
  question(query: string): Promise<string>;
}

/** Interactively asks for the domains, data directory and port, defaulting blank answers. */
export async function promptInitAnswers(prompt: PromptPort): Promise<InitAnswers> {
  const domainsRaw = await prompt.question('Domains to measure (comma-separated): ');
  const dataDirRaw = (await prompt.question(`Data directory [${DEFAULT_DATA_DIR}]: `)).trim();
  const portRaw = (await prompt.question(`Port [${DEFAULT_PORT}]: `)).trim();
  const parsedPort = portRaw.length > 0 ? Number(portRaw) : DEFAULT_PORT;

  return {
    domains: parseDomains(domainsRaw),
    dataDir: dataDirRaw.length > 0 ? dataDirRaw : DEFAULT_DATA_DIR,
    port: Number.isFinite(parsedPort) ? parsedPort : DEFAULT_PORT,
  };
}

export interface RunInitOptions {
  readonly configPath: string;
  readonly envPath: string;
  readonly force: boolean;
  readonly isInteractive: boolean;
  readonly flags: InitFlags;
  /** Required when `isInteractive` is true; ignored (flags/defaults are used instead) otherwise. */
  readonly prompt?: PromptPort | undefined;
  readonly randomBytes?: (size: number) => Uint8Array;
  readonly log: (message: string) => void;
}

/**
 * Runs `tadoru init`: resolves the answers, generates a one-time admin
 * password, and writes `tadoru.config.json` (no secret inside) plus
 * `tadoru.env` (mode 0600, holding the password). Refuses to clobber an
 * existing config unless `force` is set.
 */
export async function runInit(options: RunInitOptions): Promise<Result<void, string>> {
  if (existsSync(options.configPath) && !options.force) {
    return err(`${options.configPath} already exists. Pass --force to overwrite it.`);
  }

  const answers =
    options.isInteractive && options.prompt !== undefined
      ? await promptInitAnswers(options.prompt)
      : resolveInitAnswers({ isInteractive: options.isInteractive, flags: options.flags });
  const configObject = buildConfigFileObject(answers);
  const password = generateAdminPassword(options.randomBytes);
  const envContent = renderEnvFileContent(password);

  mkdirSync(dirname(options.configPath), { recursive: true });
  mkdirSync(dirname(options.envPath), { recursive: true });

  writeFileSync(options.configPath, `${JSON.stringify(configObject, null, 2)}\n`);
  writeFileSync(options.envPath, envContent, { mode: ENV_FILE_MODE });

  options.log(`Wrote ${options.configPath}`);
  options.log(`Wrote ${options.envPath} (mode 0600)`);
  options.log('');
  options.log(`Generated admin password: ${password}`);
  options.log('This password will not be shown again — store it somewhere safe now.');

  return ok(undefined);
}
