import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { randomBytes as nodeRandomBytes } from 'node:crypto';
import type { Result } from '../../shared/Result.ts';
import { err, ok } from '../../shared/Result.ts';
import { createSiteId } from '../domain/event/SiteId.ts';
import { DEFAULT_LOCALE, SUPPORTED_LOCALES, isSupportedLocale } from '../infrastructure/i18n/Locale.ts';
import type { Locale } from '../infrastructure/i18n/Locale.ts';

const SYSTEMD_UNIT_PATH = '/etc/systemd/system/tadoru.service';
const ETC_TADORU_DIR = '/etc/tadoru';
const ENV_FILE_PATH = '/etc/tadoru/tadoru.env';
const DEFAULT_SERVICE_USER = 'tadoru';
const ADMIN_PASSWORD_BYTE_LENGTH = 24;
const ENV_FILE_MODE = 0o600;

/**
 * Matches an actual `MemoryDenyWriteExecute=yes` directive line, but not a
 * comment merely mentioning it (the checked-in template explains in a
 * comment why it must stay absent — that line must survive).
 */
const MEMORY_DENY_WRITE_EXECUTE_LINE_PATTERN = /^\s*MemoryDenyWriteExecute\s*=\s*yes\s*$/;

/**
 * V8's JIT needs writable executable pages; Node refuses to start at all
 * under `MemoryDenyWriteExecute=yes` (see ADR 0003). The checked-in template
 * only carries a comment saying so and never sets it, but this strips the
 * directive defensively at render time regardless of what the template
 * contains, so a future edit to the template can never silently reintroduce
 * a unit that stops Node from starting.
 */
export function stripMemoryDenyWriteExecute(unit: string): string {
  return unit
    .split('\n')
    .filter((line) => !MEMORY_DENY_WRITE_EXECUTE_LINE_PATTERN.test(line))
    .join('\n');
}

export interface RenderUnitFileParams {
  readonly execPath: string;
  readonly user: string;
  readonly dataDir: string;
}

/**
 * Renders the systemd unit from the checked-in template, substituting the
 * resolved binary path, service user/group, and data directory. Always
 * strips `MemoryDenyWriteExecute=yes` from the result regardless of the
 * template's contents.
 */
export function renderUnitFile(template: string, params: RenderUnitFileParams): string {
  let rendered = template;
  rendered = rendered.replace(/^ExecStart=.*$/m, `ExecStart=${params.execPath} start`);
  rendered = rendered.replace(/^User=.*$/m, `User=${params.user}`);
  rendered = rendered.replace(/^Group=.*$/m, `Group=${params.user}`);
  rendered = rendered.replace(/^Environment=TADORU_DATA_DIR=.*$/m, `Environment=TADORU_DATA_DIR=${params.dataDir}`);
  return stripMemoryDenyWriteExecute(rendered);
}

/**
 * Parses the `--sites` flag into validated, canonicalised `SiteId`s. Invalid
 * or empty candidates are silently dropped, mirroring how `loadConfig.ts`
 * treats `TADORU_SITES` — the caller is responsible for refusing when the
 * result is empty.
 */
function parseSites(raw: string | undefined): readonly string[] {
  if (raw === undefined) return [];
  const sites: string[] = [];
  for (const candidate of raw.split(',').map((s) => s.trim()).filter((s) => s.length > 0)) {
    const result = createSiteId(candidate);
    if (result.ok) sites.push(result.value);
  }
  return sites;
}

export interface RenderEnvFileParams {
  readonly adminPassword: string;
  readonly sites: readonly string[];
  readonly lang: Locale;
}

/**
 * Renders `/etc/tadoru/tadoru.env`. Only called when the file does not
 * already exist — see `runInstallService` — so a re-run never regenerates
 * (and therefore never changes) the operator's admin password.
 */
export function renderEnvFileContent(params: RenderEnvFileParams): string {
  return [
    '# Generated by `tadoru install-service`. Keep this file at mode 0600.',
    `TADORU_ADMIN_PASSWORD=${params.adminPassword}`,
    `TADORU_SITES=${params.sites.join(',')}`,
    'TADORU_HOST=127.0.0.1',
    'TADORU_PORT=3000',
    'TADORU_TRUSTED_PROXY=true',
    `TADORU_LANG=${params.lang}`,
    '',
  ].join('\n');
}

/** Default (real) port implementations. Never exercised by tests — only the injected fakes are. */

function defaultPathExists(path: string): boolean {
  return existsSync(path);
}

function defaultUserExists(user: string): boolean {
  try {
    execFileSync('id', ['-u', user], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Creates a system user (and, via `useradd --system`'s default group
 * behaviour, a matching system group) with no home directory and no login
 * shell — a service account, not one anybody can log into.
 */
function defaultCreateSystemUser(user: string): void {
  execFileSync('useradd', ['--system', '--no-create-home', '--shell', '/usr/sbin/nologin', user], { stdio: 'ignore' });
}

function defaultMkdir(path: string): void {
  mkdirSync(path, { recursive: true });
}

/**
 * Writes with mode 0600 at creation time, so the secret is never briefly
 * world-readable. Exported (rather than kept private like the other
 * defaults) so a test can exercise the real mode contract against a temp
 * file without touching `/etc`.
 */
export function writeEnvFileToDisk(path: string, content: string): void {
  writeFileSync(path, content, { mode: ENV_FILE_MODE });
}

function defaultWriteUnitFile(path: string, content: string): void {
  writeFileSync(path, content);
}

function defaultSystemctlDaemonReload(): void {
  execFileSync('systemctl', ['daemon-reload'], { stdio: 'ignore' });
}

export interface RunInstallServiceOptions {
  readonly platform: NodeJS.Platform | string;
  /** Whether the current process is running as root (`process.getuid() === 0`). Ignored on a non-Linux platform, which is refused first regardless. */
  readonly isRoot: boolean;
  readonly dryRun: boolean;
  readonly execPath: string;
  readonly dataDir: string;
  readonly user?: string;
  /** Raw `--sites` flag value, comma-separated. At least one must validate through `createSiteId`. */
  readonly sites: string | undefined;
  /** Raw `--lang` flag value. Defaults to English when omitted; refused when set to an unsupported locale. */
  readonly lang?: string | undefined;
  readonly readTemplate: () => string;
  readonly log: (message: string) => void;
  readonly randomBytes?: (size: number) => Uint8Array;
  readonly pathExists?: (path: string) => boolean;
  readonly userExists?: (user: string) => boolean;
  readonly createSystemUser?: (user: string) => void;
  readonly mkdirEtcTadoru?: (path: string) => void;
  readonly writeEnvFile?: (path: string, content: string) => void;
  /** Only invoked outside `--dry-run`; never called in the tested dry-run path. */
  readonly writeUnitFile?: (path: string, content: string) => void;
  readonly systemctlDaemonReload?: () => void;
}

/**
 * `tadoru install-service`: prepares a fresh Linux host to run Tadoru under
 * systemd — the system user, `/etc/tadoru/`, the admin-password env file,
 * and the unit itself — then reloads systemd. It deliberately does not
 * start or enable the service: preparing the machine and starting it are
 * different decisions, and the second stays the operator's.
 *
 * Refuses outright on any non-Linux platform (systemd is Linux-only) or
 * when not run as root, before touching anything — both refusals apply even
 * under `--dry-run`. `--dry-run` only ever prints the ordered plan; every
 * effectful port stays uncalled.
 */
export async function runInstallService(options: RunInstallServiceOptions): Promise<Result<void, string>> {
  if (options.platform !== 'linux') {
    return err(
      `install-service is not supported on "${options.platform}": systemd is Linux-only. ` +
        'Run this command on the Linux server that will host Tadoru.',
    );
  }

  if (!options.isRoot) {
    return err('install-service must be run as root. Re-run it with sudo: sudo tadoru install-service ...');
  }

  const siteIds = parseSites(options.sites);
  if (siteIds.length === 0) {
    return err(
      'install-service requires at least one valid site. Pass --sites with a comma-separated ' +
        'list of domains, e.g. --sites example.com,other.dev.',
    );
  }

  if (options.lang !== undefined && !isSupportedLocale(options.lang)) {
    return err(
      `install-service: unsupported --lang "${options.lang}". Supported locales: ${SUPPORTED_LOCALES.join(', ')}.`,
    );
  }
  const lang: Locale = options.lang !== undefined && isSupportedLocale(options.lang) ? options.lang : DEFAULT_LOCALE;

  const user = options.user ?? DEFAULT_SERVICE_USER;
  const template = options.readTemplate();
  const rendered = renderUnitFile(template, { execPath: options.execPath, user, dataDir: options.dataDir });

  if (options.dryRun) {
    options.log('--dry-run: nothing was written. This install would, in order:');
    options.log(`  1. Create the "${user}" system user and group, if missing (no home, no login shell)`);
    options.log(`  2. Create ${ETC_TADORU_DIR}`);
    options.log(`  3. Write ${ENV_FILE_PATH} (mode 0600) with a freshly generated admin password — kept as is if it already exists`);
    options.log(`  4. Write ${SYSTEMD_UNIT_PATH}`);
    options.log('  5. Run systemctl daemon-reload');
    options.log('  6. Print the generated admin password once');
    options.log('');
    options.log('Rendered unit:');
    options.log(rendered);
    return ok(undefined);
  }

  const pathExists = options.pathExists ?? defaultPathExists;
  const userExists = options.userExists ?? defaultUserExists;
  const createSystemUser = options.createSystemUser ?? defaultCreateSystemUser;
  const mkdirEtcTadoru = options.mkdirEtcTadoru ?? defaultMkdir;
  const writeEnvFile = options.writeEnvFile ?? writeEnvFileToDisk;
  const writeUnitFile = options.writeUnitFile ?? defaultWriteUnitFile;
  const systemctlDaemonReload = options.systemctlDaemonReload ?? defaultSystemctlDaemonReload;
  const randomBytesFn = options.randomBytes ?? nodeRandomBytes;

  if (userExists(user)) {
    options.log(`User "${user}" already exists; leaving it as is.`);
  } else {
    createSystemUser(user);
    options.log(`Created system user and group "${user}" (no home directory, no login shell).`);
  }

  mkdirEtcTadoru(ETC_TADORU_DIR);
  options.log(`Ensured ${ETC_TADORU_DIR} exists.`);

  let generatedPassword: string | undefined;
  if (pathExists(ENV_FILE_PATH)) {
    options.log(`${ENV_FILE_PATH} already exists; keeping it unchanged.`);
  } else {
    generatedPassword = Buffer.from(randomBytesFn(ADMIN_PASSWORD_BYTE_LENGTH)).toString('base64url');
    const envContent = renderEnvFileContent({ adminPassword: generatedPassword, sites: siteIds, lang });
    writeEnvFile(ENV_FILE_PATH, envContent);
    options.log(`Wrote ${ENV_FILE_PATH} (mode 0600).`);
  }

  writeUnitFile(SYSTEMD_UNIT_PATH, rendered);
  options.log(`Wrote ${SYSTEMD_UNIT_PATH}.`);

  systemctlDaemonReload();
  options.log('Ran systemctl daemon-reload.');

  options.log('');
  if (generatedPassword !== undefined) {
    options.log(`Generated admin password: ${generatedPassword}`);
    options.log('This password will not be shown again — store it somewhere safe now.');
  } else {
    options.log(`Admin password unchanged (kept the existing ${ENV_FILE_PATH}).`);
  }
  options.log('');
  options.log('Review the unit, then start it when ready:');
  options.log('  sudo systemctl enable --now tadoru');

  return ok(undefined);
}

export function readSystemdTemplate(templatePath: string): string {
  return readFileSync(templatePath, 'utf8');
}
