import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  envBackupFileName,
  resolveEnvBackupPath,
  rewriteCredentialLines,
  runResetPassword,
  writeEnvFileToDisk,
} from './resetPassword.ts';
import type { RunResetPasswordOptions } from './resetPassword.ts';
import { verifyPasswordHash } from '../infrastructure/http/adminAuth.ts';

async function withTempDirAsync<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const dir = mkdtempSync(join(tmpdir(), 'tadoru-reset-password-test-'));
  try {
    return await fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function baseOptions(overrides: Partial<RunResetPasswordOptions> = {}) {
  const logs: string[] = [];
  const calls: { readonly port: string; readonly args: readonly unknown[] }[] = [];

  const options: RunResetPasswordOptions = {
    isRoot: true,
    dryRun: false,
    envFilePath: '/etc/tadoru/tadoru.env',
    log: (message: string) => logs.push(message),
    randomBytes: (size: number) => new Uint8Array(size).fill(9),
    pathExists: (path: string) => {
      calls.push({ port: 'pathExists', args: [path] });
      return true;
    },
    readEnvFile: (path: string) => {
      calls.push({ port: 'readEnvFile', args: [path] });
      return '# a comment\nTADORU_ADMIN_PASSWORD_HASH=oldhash\nTADORU_ADMIN_PASSWORD_SALT=oldsalt\nTADORU_SITES=example.com\n';
    },
    backupEnvFile: (source: string, backup: string) => {
      calls.push({ port: 'backupEnvFile', args: [source, backup] });
    },
    writeEnvFile: (path: string, content: string) => {
      calls.push({ port: 'writeEnvFile', args: [path, content] });
    },
    now: () => new Date('2026-09-09T10:20:30.000Z'),
    ...overrides,
  };

  return { options, logs, calls };
}

// ---------------------------------------------------------------------------
// rewriteCredentialLines
// ---------------------------------------------------------------------------

test('rewriteCredentialLines replaces existing hash/salt lines in place, preserving everything else', () => {
  const content = [
    '# Generated by `tadoru install-service`. Keep this file at mode 0600.',
    'TADORU_ADMIN_PASSWORD_HASH=oldhash',
    'TADORU_ADMIN_PASSWORD_SALT=oldsalt',
    'TADORU_SITES=example.com',
    'TADORU_HOST=127.0.0.1',
    '',
  ].join('\n');

  const rewritten = rewriteCredentialLines(content, 'newhash', 'newsalt');
  const lines = rewritten.split('\n');

  assert.deepEqual(lines, [
    '# Generated by `tadoru install-service`. Keep this file at mode 0600.',
    'TADORU_ADMIN_PASSWORD_HASH=newhash',
    'TADORU_ADMIN_PASSWORD_SALT=newsalt',
    'TADORU_SITES=example.com',
    'TADORU_HOST=127.0.0.1',
    '',
  ]);
});

test('rewriteCredentialLines removes an old plaintext TADORU_ADMIN_PASSWORD line and replaces it with hash+salt', () => {
  const content = [
    '# a hand-written comment an operator added',
    'TADORU_ADMIN_PASSWORD=old-plaintext-value',
    '',
    'TADORU_SITES=example.com',
  ].join('\n');

  const rewritten = rewriteCredentialLines(content, 'newhash', 'newsalt');

  assert.doesNotMatch(rewritten, /^TADORU_ADMIN_PASSWORD=/m);
  assert.match(rewritten, /^TADORU_ADMIN_PASSWORD_HASH=newhash$/m);
  assert.match(rewritten, /^TADORU_ADMIN_PASSWORD_SALT=newsalt$/m);
  // Unrelated lines, including the blank line and the operator's own comment, survive verbatim.
  assert.match(rewritten, /^# a hand-written comment an operator added$/m);
  assert.match(rewritten, /^TADORU_SITES=example\.com$/m);
});

test('rewriteCredentialLines leaves exactly one credential pair when plaintext precedes hash and salt lines', () => {
  // An env file part-way through the migration: the old plaintext line is still
  // there, above the hash+salt pair a later `install-service` run appended. The
  // plaintext line is the one replaced in place, so the real hash and salt lines
  // further down must be dropped rather than emitted a second time.
  const content = [
    'TADORU_ADMIN_PASSWORD=old-plaintext-value',
    'TADORU_SITES=example.com',
    'TADORU_ADMIN_PASSWORD_HASH=oldhash',
    'TADORU_ADMIN_PASSWORD_SALT=oldsalt',
  ].join('\n');

  const rewritten = rewriteCredentialLines(content, 'newhash', 'newsalt');

  const hashLines = rewritten.split('\n').filter((line) => line.startsWith('TADORU_ADMIN_PASSWORD_HASH='));
  const saltLines = rewritten.split('\n').filter((line) => line.startsWith('TADORU_ADMIN_PASSWORD_SALT='));
  assert.deepEqual(hashLines, ['TADORU_ADMIN_PASSWORD_HASH=newhash']);
  assert.deepEqual(saltLines, ['TADORU_ADMIN_PASSWORD_SALT=newsalt']);
  assert.doesNotMatch(rewritten, /^TADORU_ADMIN_PASSWORD=/m);
  assert.match(rewritten, /^TADORU_SITES=example\.com$/m);
});

test('rewriteCredentialLines appends hash+salt when no credential line exists at all', () => {
  const content = 'TADORU_SITES=example.com\n';
  const rewritten = rewriteCredentialLines(content, 'newhash', 'newsalt');
  assert.match(rewritten, /^TADORU_SITES=example\.com$/m);
  assert.match(rewritten, /^TADORU_ADMIN_PASSWORD_HASH=newhash$/m);
  assert.match(rewritten, /^TADORU_ADMIN_PASSWORD_SALT=newsalt$/m);
});

// ---------------------------------------------------------------------------
// envBackupFileName / resolveEnvBackupPath
// ---------------------------------------------------------------------------

test('envBackupFileName encodes the date and time in a filesystem-safe way', () => {
  const name = envBackupFileName(new Date('2026-09-09T10:20:30.000Z'));
  assert.equal(name, 'tadoru.env.bak-2026-09-09T10-20-30');
});

test('resolveEnvBackupPath places the backup alongside the env file', () => {
  const path = resolveEnvBackupPath('/etc/tadoru/tadoru.env', 'tadoru.env.bak-2026-09-09T10-20-30');
  assert.equal(path, join('/etc/tadoru', 'tadoru.env.bak-2026-09-09T10-20-30'));
});

// ---------------------------------------------------------------------------
// runResetPassword — refusals
// ---------------------------------------------------------------------------

test('runResetPassword refuses when not run as root', async () => {
  const { options, calls } = baseOptions({ isRoot: false });
  const result = await runResetPassword(options);
  assert.equal(result.ok, false);
  if (!result.ok) {
    assert.match(result.error, /root/i);
    assert.match(result.error, /sudo/i);
  }
  assert.equal(calls.length, 0);
});

test('runResetPassword refuses when the env file does not exist, and points at install-service', async () => {
  const { options, calls } = baseOptions({ pathExists: () => false });
  const result = await runResetPassword(options);
  assert.equal(result.ok, false);
  if (!result.ok) {
    assert.match(result.error, /does not exist/i);
    assert.match(result.error, /install-service/);
  }
  assert.ok(!calls.some((c) => c.port === 'writeEnvFile'));
  assert.ok(!calls.some((c) => c.port === 'backupEnvFile'));
});

// ---------------------------------------------------------------------------
// runResetPassword — dry-run
// ---------------------------------------------------------------------------

test('runResetPassword --dry-run performs no filesystem effect', async () => {
  const { options, logs, calls } = baseOptions({ dryRun: true });
  const result = await runResetPassword(options);
  assert.equal(result.ok, true);
  assert.ok(!calls.some((c) => c.port === 'writeEnvFile'));
  assert.ok(!calls.some((c) => c.port === 'backupEnvFile'));
  assert.ok(!calls.some((c) => c.port === 'readEnvFile'));
  assert.match(logs.join('\n'), /dry-run/i);
});

test('runResetPassword --dry-run still refuses when not root', async () => {
  const { options, calls } = baseOptions({ dryRun: true, isRoot: false });
  const result = await runResetPassword(options);
  assert.equal(result.ok, false);
  assert.equal(calls.length, 0);
});

test('runResetPassword --dry-run still refuses when the env file is missing', async () => {
  const { options, calls } = baseOptions({ dryRun: true, pathExists: () => false });
  const result = await runResetPassword(options);
  assert.equal(result.ok, false);
  assert.ok(!calls.some((c) => c.port === 'writeEnvFile'));
});

// ---------------------------------------------------------------------------
// runResetPassword — real rewrite
// ---------------------------------------------------------------------------

test('runResetPassword preserves unrelated lines and comments, only touching credential lines', async () => {
  const { options, calls } = baseOptions();
  const result = await runResetPassword(options);
  assert.equal(result.ok, true);

  const writeCall = calls.find((c) => c.port === 'writeEnvFile');
  assert.ok(writeCall);
  const content = writeCall.args[1] as string;
  assert.match(content, /^# a comment$/m);
  assert.match(content, /^TADORU_SITES=example\.com$/m);
  assert.doesNotMatch(content, /oldhash|oldsalt/);
});

test('runResetPassword backs up the existing env file before rewriting it', async () => {
  const { options, calls } = baseOptions();
  const result = await runResetPassword(options);
  assert.equal(result.ok, true);

  const backupIndex = calls.findIndex((c) => c.port === 'backupEnvFile');
  const writeIndex = calls.findIndex((c) => c.port === 'writeEnvFile');
  assert.ok(backupIndex !== -1, 'backupEnvFile must be called');
  assert.ok(backupIndex < writeIndex, 'the backup must happen before the file is rewritten');

  const backupCall = calls[backupIndex];
  assert.equal(backupCall?.args[0], options.envFilePath);
  assert.match(backupCall?.args[1] as string, /tadoru\.env\.bak-/);
});

test('runResetPassword prints the new password to stdout exactly once, with a restart reminder, and never passes it to writeEnvFile/backupEnvFile as an argument', async () => {
  const { options, logs, calls } = baseOptions();
  const result = await runResetPassword(options);
  assert.equal(result.ok, true);

  const output = logs.join('\n');
  const matches = [...output.matchAll(/New admin password: (\S+)/g)];
  assert.equal(matches.length, 1, 'the password must be printed exactly once');
  const password = matches[0]?.[1] as string;
  assert.ok(password.length > 0);
  assert.match(output, /will not be shown again/i);
  assert.match(output, /sudo systemctl restart tadoru/);

  for (const call of calls) {
    if (call.port === 'writeEnvFile') continue; // the hash+salt derived from it legitimately live in the content
    for (const arg of call.args) {
      assert.ok(typeof arg !== 'string' || !arg.includes(password), `password leaked into a ${call.port} argument`);
    }
  }
  // Even writeEnvFile's content must carry the derived hash, never the plaintext password itself.
  const writeCall = calls.find((c) => c.port === 'writeEnvFile');
  assert.ok(writeCall && !(writeCall.args[1] as string).includes(password));
});

test('runResetPassword exits with a non-ok Result on every refusal (root, missing file)', async () => {
  const notRoot = await runResetPassword(baseOptions({ isRoot: false }).options);
  const missingFile = await runResetPassword(baseOptions({ pathExists: () => false }).options);
  assert.equal(notRoot.ok, false);
  assert.equal(missingFile.ok, false);
});

// ---------------------------------------------------------------------------
// No spawn/exec-style port exists for this command at all — by construction,
// the generated password can never be passed across a shell/process boundary.
// ---------------------------------------------------------------------------

test('resetPassword.ts defines no spawn/exec-style port that could receive the password', () => {
  const sourcePath = fileURLToPath(new URL('./resetPassword.ts', import.meta.url));
  const source = readFileSync(sourcePath, 'utf8');
  assert.doesNotMatch(source, /execFileSync|execSync|spawnSync|spawn\(|child_process/);
});

// ---------------------------------------------------------------------------
// Real port implementations, wired end to end against a temp file.
// ---------------------------------------------------------------------------

test('runResetPassword, wired to the real ports, rewrites a real env file and keeps it at mode 0600', async () => {
  await withTempDirAsync(async (dir) => {
    {
      const envPath = join(dir, 'tadoru.env');
      writeFileSync(
        envPath,
        '# operator comment\nTADORU_ADMIN_PASSWORD_HASH=oldhash\nTADORU_ADMIN_PASSWORD_SALT=oldsalt\nTADORU_SITES=example.com\n',
        { mode: 0o600 },
      );

      const { existsSync, readFileSync: realReadFileSync, copyFileSync } = await import('node:fs');
      const result = await runResetPassword({
        isRoot: true,
        dryRun: false,
        envFilePath: envPath,
        log: () => {},
        randomBytes: (size: number) => new Uint8Array(size).fill(3),
        pathExists: existsSync,
        readEnvFile: (p: string) => realReadFileSync(p, 'utf8'),
        backupEnvFile: (source: string, backup: string) => copyFileSync(source, backup),
        writeEnvFile: writeEnvFileToDisk,
        now: () => new Date('2026-09-09T10:20:30.000Z'),
      });

      assert.equal(result.ok, true);
      const mode = statSync(envPath).mode & 0o777;
      assert.equal(mode, 0o600);

      const rewritten = readFileSync(envPath, 'utf8');
      assert.match(rewritten, /^# operator comment$/m);
      assert.match(rewritten, /^TADORU_SITES=example\.com$/m);
      assert.doesNotMatch(rewritten, /oldhash|oldsalt/);

      const backupPath = join(dir, 'tadoru.env.bak-2026-09-09T10-20-30');
      assert.ok(existsSync(backupPath), 'a dated backup must exist');
      assert.match(readFileSync(backupPath, 'utf8'), /oldhash/);
    }
  });
});

test('runResetPassword, wired to the real ports, produces a hash+salt pair that verifies against the printed password', async () => {
  await withTempDirAsync(async (dir) => {
    {
      const envPath = join(dir, 'tadoru.env');
      writeFileSync(envPath, 'TADORU_ADMIN_PASSWORD_HASH=oldhash\nTADORU_ADMIN_PASSWORD_SALT=oldsalt\n', { mode: 0o600 });

      const { existsSync, readFileSync: realReadFileSync, copyFileSync } = await import('node:fs');
      const logs: string[] = [];
      const result = await runResetPassword({
        isRoot: true,
        dryRun: false,
        envFilePath: envPath,
        log: (m: string) => logs.push(m),
        pathExists: existsSync,
        readEnvFile: (p: string) => realReadFileSync(p, 'utf8'),
        backupEnvFile: (source: string, backup: string) => copyFileSync(source, backup),
        writeEnvFile: writeEnvFileToDisk,
      });
      assert.equal(result.ok, true);

      const printedPassword = /New admin password: (\S+)/.exec(logs.join('\n'))?.[1] as string;
      const content = readFileSync(envPath, 'utf8');
      const hash = /^TADORU_ADMIN_PASSWORD_HASH=([0-9a-f]+)$/m.exec(content)?.[1] as string;
      const salt = /^TADORU_ADMIN_PASSWORD_SALT=([0-9a-f]+)$/m.exec(content)?.[1] as string;
      assert.equal(verifyPasswordHash(printedPassword, { hash, salt }), true);
    }
  });
});
